# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# twitter:
#   username: krrish94 # jekyll-seo-tag > Owners twitter username
author: MontrealRobotics # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: MontrealRobotics # jekyll-seo-tag > real name
  # links:  # jekyll-seo-tag > social aliases (sameAs)
  #   - https://twitter.com/DavidDarnes
  #   - https://www.facebook.com/daviddarnes
  #   - https://www.linkedin.com/in/daviddarnes
  #   - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# # 5. Collections
# collections:
#   posts:
#     title: Posts # Needed for Siteleaf
#     output: true
#     description: "My thoughts and ideas" # The post list page content
#     feature_text: |
#       Welcome to the blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "assets/default-social-image.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Robot learning seminar - Mila" # Site name or title, also used in jekyll-seo-tag
logo: "assets/img/favicon.png" # Site logo, also used in jekyll-seo-tag
description: "Robot learning seminar, Fall 2020" # Site description and default description, also used in jekyll-seo-tag
url: "https://montrealrobotics.ca/robotlearningseminar" # Site url, also used in jekyll-seo-tag
baseurl: "https://montrealrobotics.ca/robotlearningseminar/"
baseurl: ""
repo: "https://github.com/montrealrobotics/robotlearningseminar"
email: "krrish94@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'UA-130243767-1'
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  270: "assets/img/favicon.png"

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Summer 2020
  url: /summer2020/
# - title: Elements
#   url: /elements/
# - title: Blog
#   url: /blog/
# - title: Categories
#   url: /categories/
# - title: Search
#   url: /search/
# - title: Fork Alembic
#   url: https://github.com/daviddarnes/alembic

navigation_footer:
- title: Based on the Alembic theme by David Darnes
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  # Twitter: https://twitter.com/DavidDarnes
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # GitHub: https://github.com/daviddarnes
  link: https://montrealrobotics.ca
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
